---
:concurrency: 10

# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 10

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
:queues:
  - [critical, 12]
  - [mailers, 6]
  - [default, 6]
  - [low, 3]

# you can override concurrency based on environment
production:
  :concurrency: 25
staging:
  :concurrency: 15